services:
  todoist-exporter:
    image: ghcr.io/echohello-dev/prometheus-todoist-exporter:latest
    container_name: todoist-exporter
    restart: unless-stopped
    ports:
      - "9090:9090"
    environment:
      - TODOIST_API_TOKEN=${TODOIST_API_TOKEN}
      - EXPORTER_PORT=9090
      - METRICS_PATH=/metrics
      - COLLECTION_INTERVAL=60
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}