version: '3'

dotenv:
  - .env

tasks:
  install:
    desc: Install dependencies with Poetry
    cmds:
      - "poetry install"

  format:
    desc: Format the code with ruff
    cmds:
      - "poetry run ruff format ."

  lint:
    desc: Run linting checks
    cmds:
      - "poetry run ruff check ."

  lint-fix:
    desc: Run linting and fix issues
    cmds:
      - "poetry run ruff check --fix ."

  test:
    desc: Run tests
    cmds:
      - "poetry run pytest"

  run:
    desc: Run the Todoist exporter locally
    cmds:
      - "poetry run todoist-exporter"

  pre-commit-install:
    desc: Install pre-commit hooks
    cmds:
      - "poetry run pre-commit install"

  pre-commit-run:
    desc: Run pre-commit checks on all files
    cmds:
      - "poetry run pre-commit run --all-files"

  pre-commit-update:
    desc: Update pre-commit hooks to the latest version
    cmds:
      - "poetry run pre-commit autoupdate"

  docker-build:
    desc: Build the Docker image locally
    cmds:
      - docker build -t ghcr.io/echohello-dev/prometheus-todoist-exporter:latest .

  docker-run:
    desc: Run the Docker container locally
    cmds:
      - docker run -p 9090:9090 -e TODOIST_API_TOKEN=${TODOIST_API_TOKEN} ghcr.io/echohello-dev/prometheus-todoist-exporter:latest

  docker-compose-up:
    desc: Run using Docker Compose
    cmds:
      - docker compose up -d

  docker-compose-down:
    desc: Stop docker-compose services
    cmds:
      - docker compose down

  setup-dev:
    desc: Setup local development environment
    cmds:
      - cp -n .env.example .env || true
      - echo "Created .env file from .env.example (if it didn't already exist). Please update with your TODOIST_API_TOKEN."
      - task install
      - task pre-commit-install

  setup:
    desc: Setup
    cmds:
      - |
        if ! command -v asdf &> /dev/null; then
          echo "asdf not found, installing..."
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.11.3 || true
          echo 'source ~/.asdf/asdf.sh' >> ~/.bashrc
          echo 'source ~/.asdf/completions/asdf.bash' >> ~/.bashrc
          source ~/.asdf/asdf.sh
        fi
      - asdf plugin add python
      - asdf plugin add task
      - asdf install
      - pip install poetry
      - asdf reshim python
      - task setup-dev

  all:
    desc: Run format, lint, and test tasks
    deps: [format, lint, test]

  publish-pypi:
    desc: Publish to PyPI
    cmds:
      - poetry publish --build

  k8s-deploy:
    desc: Deploy to Kubernetes using kustomize
    cmds:
      - |
        if [ -z "${TODOIST_API_TOKEN}" ]; then
          echo "Error: TODOIST_API_TOKEN environment variable is not set"
          exit 1
        fi
      - kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
      - |
        TODOIST_API_TOKEN_B64=$(echo -n "${TODOIST_API_TOKEN}" | base64)
        sed "s/<BASE64_ENCODED_API_TOKEN>/$TODOIST_API_TOKEN_B64/" deploy/kubernetes/secret.yaml | kubectl apply -f -
      - kubectl apply -k deploy/kubernetes

  k8s-delete:
    desc: Delete Kubernetes deployment
    cmds:
      - kubectl delete -k deploy/kubernetes
      - echo "You may want to delete the namespace with 'kubectl delete namespace monitoring' if it's no longer needed"

  helm-deploy:
    desc: Deploy using Helm chart
    cmds:
      - |
        if [ -z "${TODOIST_API_TOKEN}" ]; then
          echo "Error: TODOIST_API_TOKEN environment variable is not set"
          exit 1
        fi
      - helm upgrade --install todoist-exporter ./deploy/helm/prometheus-todoist-exporter --namespace monitoring --create-namespace --set todoist.apiToken="${TODOIST_API_TOKEN}"

  helm-delete:
    desc: Delete Helm deployment
    cmds:
      - helm uninstall todoist-exporter --namespace monitoring
      - echo "You may want to delete the namespace with 'kubectl delete namespace monitoring' if it's no longer needed"

  helm-lint:
    desc: Lint the Helm chart
    cmds:
      - helm lint ./deploy/helm/prometheus-todoist-exporter

  helm-template:
    desc: Generate Kubernetes manifests from Helm chart
    cmds:
      - helm template todoist-exporter ./deploy/helm/prometheus-todoist-exporter --namespace monitoring --set todoist.apiToken="dummy-value"
