apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-todoist-exporter.fullname" . }}
  labels:
    {{- include "prometheus-todoist-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prometheus-todoist-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prometheus-todoist-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prometheus-todoist-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.exporter.port }}
              protocol: TCP
          env:
            - name: TODOIST_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "prometheus-todoist-exporter.fullname" . }}
                  key: api-token
            - name: EXPORTER_PORT
              value: "{{ .Values.exporter.port }}"
            - name: METRICS_PATH
              value: "{{ .Values.exporter.metricsPath }}"
            - name: COLLECTION_INTERVAL
              value: "{{ .Values.exporter.collectionInterval }}"
            - name: COMPLETED_TASKS_DAYS
              value: "{{ .Values.exporter.completedTasksDays }}"
            - name: COMPLETED_TASKS_HOURS
              value: "{{ .Values.exporter.completedTasksHours }}"
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
