apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-todoist-exporter.fullname" . }}
  labels:
    {{- include "prometheus-todoist-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  api-token: {{ .Values.todoist.apiToken | b64enc | quote }}
